// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeraw-d6h4LXFl0O3AvuHroJEWziymqJ0',
    appId: '1:496544565345:web:15c1d5b5436ae7feffc220',
    messagingSenderId: '496544565345',
    projectId: 'ojtara-app',
    authDomain: 'ojtara-app.firebaseapp.com',
    storageBucket: 'ojtara-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZEbXlwIBQEGeh8NfrofbbjlsbUDl12O4',
    appId: '1:496544565345:android:9e8713d3c10ec589ffc220',
    messagingSenderId: '496544565345',
    projectId: 'ojtara-app',
    storageBucket: 'ojtara-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjCwIf9jnsUctbmVFhzU-Ypl7_3KM8ASQ',
    appId: '1:496544565345:ios:ed85f1cb85e10c1fffc220',
    messagingSenderId: '496544565345',
    projectId: 'ojtara-app',
    storageBucket: 'ojtara-app.firebasestorage.app',
    iosBundleId: 'com.example.ojtaraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjCwIf9jnsUctbmVFhzU-Ypl7_3KM8ASQ',
    appId: '1:496544565345:ios:ed85f1cb85e10c1fffc220',
    messagingSenderId: '496544565345',
    projectId: 'ojtara-app',
    storageBucket: 'ojtara-app.firebasestorage.app',
    iosBundleId: 'com.example.ojtaraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeraw-d6h4LXFl0O3AvuHroJEWziymqJ0',
    appId: '1:496544565345:web:6cfd68316a5ac631ffc220',
    messagingSenderId: '496544565345',
    projectId: 'ojtara-app',
    authDomain: 'ojtara-app.firebaseapp.com',
    storageBucket: 'ojtara-app.firebasestorage.app',
  );
}
